# Closing

Ingenious Growth Hacks
 
While each of these companies offer excellent examples of growth hacking in action, everyone seems to want to arrive at the “top” growth hacks of all time list. I’ve already talked about the AirBnB hack to integrate under the radar with Craigslist, but here’s a compilation (in no particular order) of some of the tactics that always seem to make the cut:
Hotmail really is considered one of the classics of growth hacking, and it was a simplistic and ingenious move. That tag line at the bottom of every email, “Get your free email at Hotmail,” took the service from 3000 users to 1 million in 6 months. That one probably will always hold first place on any list because it was and is brilliant.
 
The Facebook option to tag someone in a photo sends an email to that person, an action that generates almost a 75% click through rate to the site. The emotional pull is almost irresistible. What’s the picture? What did they say? Is my Mother going to see that? In a true culture of growth, Facebook still has a growth team, even though it’s the largest social network in the world.
 
The Dropbox option to invite a friend and get 500mb of storage kicks up the user’s social reaction and self-interest. Once a Dropbox user really understands what the service can do for them, especially in storing and sharing large photo files, the desire for more space at no cost is almost automatic. 
Pinterest applies an incredibly simple way to remove any perceived friction from their browsing experience – the ultimate scroll. You can go to Pinterest and look, and look, and look, and look and never click once. Are people really that lazy? Absolutely, but at the same time, this technique creates stickiness and ultimately will draw them deeper and deeper into the site.
 
Instagram does something similar with their feed via their mobile app. To speed load time, they put only the most popular photos first, which encourages scrolling and encourages users to add and share their own photos. Both Pinterest and Instagram are heavily dependent on the power of visual appeal and have optimized their feeds brilliantly to capitalize on that experience.

 
There are some pretty brilliant game-based growth hacks out there as well. In mid-2013, the game Candy Crush was reporting 45 million users per month. How? By its very design Candy Crush creates sweet tooth addicts. When a user “dies,” they either have to wait 30 minutes for a timer reset, pay for more lives to play again, or go out begging / inviting friends to sign up and help them out.

Learning to Growth Hack
 
It’s important to understand from the beginning that there is no one way to achieve company growth. In fact, the very nature of growth hacking pushes against complacency and formulaic approaches.
 No growth hacker should ever see their role in a company as static, nor should they look for growth that follows a single curve.
 Truly effective growth is both steady and rapid. The best curve to grow a business looks more like a jagged set of steps going up the side of a mountain than a smooth curve. Think about that image for a minute.
Periods of slow, steady growth allow for testing, development, and strategic planning.
 
Periods of rapid, unsustainable growth achieve new plateaus, infuse the endeavor with energy, and if well analyzed, suggest new directions.
 
Merged into one upward pattern, these two types of growth represent true and building momentum.
 
Art, Not Science
 Remember, growth hacking is more art than science and demands that the growth hacker have the ability to constantly adapt to an organization’s changing needs. People who like routine or who are wedded to doing things one way for long periods of time don’t make good growth hackers!
 
Always ask yourself: 
What does the customer or the market want?
Who are my customers / users?
Where do I find my customers / users?
What language do my customers / users speak?

It’s a wise course of action to do NOTHING until you know your market. Just look at Goodreads and Amazon.
 Goodreads was founded by a voracious reader who also happened to be a coder. Amazon was founded by an entrepreneur who looked at what could be sold online and settled on books due to historic demand and the passionate attachment of readers to literature.
 It’s worth noting that Jeff Bezos ruled out video, audio, and computers as the basis for the Amazon store, but then came back when he had the capital and incorporated those items and many more into the now giant retail site.
 His reason for the gradual expansion was incredibly sound. People who buy books also tend to buy music and videos. He then merged those interests into a neat consumer electronics package with the Kindle Fire tablet, an all-in-one device for consuming Amazon content — ebooks, music, and video with built-in on-the-device ordering. Now THAT’S knowing your market.
 It didn’t happen all at once, but Bezos understood the desires of his customers and has continued to innovate in a direction that meets their growing and changing tastes. Oh. And along the way, he bought Goodreads, the largest online social community for readers and completely integrated its use in the Kindle line of ebook readers. Genius.
 
A Growth Oriented Company Culture
 It’s good wisdom to follow the dictate that the concept of growth has to be hardwired into a business or product from day one — as the example of Jeff Bezos clearly illustrates.
 Ideally, this attitude should be cultivated by the founder of the endeavor as the one who sets the tone for a growth “creed” and directs the allocation of resources to realize that vision. Typically the realization happens along the lines of the curve I described in the opening of this chapter, sharp growth spikes punctuated with plateaus for measurement and reassessment.
 In a best-case-scenario the founder of a company is also the endeavor’s first and chief growth hacker, even though he is likely to pass that responsibility on to others once the business is out of the startup phase.
 People who successfully grow businesses tend to be generalists, a trait often seen in successful entrepreneurs — and they should also have vision. That translates to good intuition for product, and an ability to fill multiple roles while keeping their eyes on the ultimate goal.
 
All Growth Hackers Aren’t Coders
 
It’s a mistake, however, to assume that all growth hackers also have to be coders. Certainly it’s an ideal situation if you have someone who is both a software engineer and a brilliant, innovative marketer with a sense of product-market fit.
 Those people are, however, about as common as mythical unicorns. If you can articulate your needs and explain how you perceive gaining initial traction, software engineers can be hired to make it happen.
 The same results can be achieved by either party, it’s simply a matter of how the questions are posed to trigger the development of solutions.
A growth hacker who is a coder might look at an aspect of the user experience and think, “There has to be a way to automate that.”
 
A growth hacker who isn’t a coder is the guy who walks into the software engineer’s office and says, “Do you think you can find a way to automate that?”
 
The two types can be very powerful partners since coders tend to become growth hackers the longer they are a part of a growth hacking team. By nature their minds are analytical and trend toward problem solving.
 Most programmers have, at one time or another, chafed under the constraints of the limited imagination of management. Growth hacking is about testing, measuring, and trying out new concepts.
 Creative people thrive in that environment and although they may not consider themselves growth hackers in the beginning, they are often the very ones to say, “Hey, what would happen if . . . ?”
 When the person listening to creative ideas that fall outside of the proverbial box is open and receptive to innovation, the whole team effort becomes supercharged.
 The take away from these observations is to develop a sound concept and never stop working to find and hone market fit. Hire the best people you can find. Share your vision. Make sure they understand it. And then work the data over and over again.
 
Replicable Strategies are Golden
 Any strategy that can be used repeatedly and gets better with each iteration is golden. Companies like Uber are a good example. They perfected a city-wide roll out strategy in San Francisco that proved to be so effective they have used and improved it in each successive city they enter.
 Even in the face of replicable success, however, the focus should remain on delivering the best user / customer experience, even if that means completely changing the direction of the endeavor midstream. RelayRides is a good example of an incredibly successful change in course.
 They started out believing that their ride sharing concept was best targeted for short-term hourly hires and wound up completely focusing their business on long-term rentals with airport based drop off and pick up. Why?
 The company introduced its service at San Francisco International Airport where it was so well received, the concept was then implemented in 229 additional airports. In short order, RelayRides was gaining 95% of their revenue from a long-term hiring model and discontinued hourly rentals.
 A replicable growth hacking strategy for a company might look something like this:

Figure out what data to track that will give you the greatest insight into your user base and its behavior.
Perform the necessary analytics to understand that behavior and extract the maximum benefit and insight from it.
Prioritize the actions that will most facilitate growth and do those first, even if redesign or the inclusion of new features and/or directions is required.
Build and push changes as reflected under prioritization. Measure again and gauge your success.

 
Obviously these steps are customized per product and business model, but you get the idea. Test, refine, implement — over, and over, and over again.
 
Markets Are Always in Flux
 Never fall into the trap of assuming you have achieved perfect market fit. Markets are constantly in flux. What you do to gain traction in a market may not be the answer to sustaining and growing your user base. Almost all of the truly great growth hacks are, at the base level, answers to optimization problems.
The Hotmail tagline was a simple and elegant refinement to every email message sent through the service that made each email a marketing tool.
 
The AirBnB hack neatly cross-posted listings to Craigslist, bootstrapping the booking service’s user base off the existing Craiglist ecosystem.
 
The Pinterest invite-only beta successfully generated interest and seeded the site with high quality pins from professional designers.
 
Each of these growth hacks and less flashy techniques like Twitter’s suggested followers, Instagram’s cross-posting options, and Dropox’s incentivized referrals are all examples of optimizing presentation and enhancing the user experience.
 There is no such thing as “good enough” in growth hacking, where even shaving a few seconds off a site’s load time can have value if it answers a clearly 
 
identified user need or removes a potential point of friction.
 Scrappy, even black hat, techniques like AirBnB’s hack of Craigslist may be responsible for first stage growth, but the problems generally get more complicated when retention, monetization, and acquisition enter the equation.
 Lots of startups take off like a rocket only to fizzle for lack of sustained growth. Always maintain the attitude that something you are doing can be done better.
 
“Do or Do Not, There is No Try”
 
Okay, yeah, I blatantly lifted that from Yoda, but in the end result the way to learn to growth hack is to growth hack — not to try it, but just to do it. One of the most attractive aspects of this philosophy of marketing is that mistakes aren’t just “allowed,” but are a good thing because they are taken as opportunities from which people just move on.
 “Do overs” are encouraged and changing your mind is a virtue, but ONLY when done in the name of achieving the ultimate goal of growth and ONLY in response to measurable data reflecting user behavior and articulated needs. This is the matter of “product / market fit” and it’s EVERYTHING. While you’re working your own growth hacking strategies, immerse yourself in what other growth hackers are doing. Read case studies like those I have included in this text. Get ideas from idea people. The specific growth hack may not apply to your product or your business model, but it might inspire you to do something similar — or even NOT to do something.
 
Growth Hacking Reference Sources
 
There are a plethora of online resources on growth hacking to broaden your understanding and learn from the “masters.” Here are some of my favorites to get you started:
“What is ‘Growth Hacking’ Really?” by Josh Elan at medium.com/what-i-learned-building/f445b04cbd20

“Defining A Growth Hacker: Three Common Characteristics” at techcrunch.com/2012/09/02/defining-a-growthhacker-three-common-characteristics

“The Definitive Guide to Growth Hacking” at www.quicksprout.com/2013/08/26/the-definitive-guide-togrowthhacking/

“Defining A Growth Hacker: Debunking The 6 Most Common Myths About Growth Hacking” at techcrunch.com/2012/12/08/defining-agrowthhacker-6-myths-about-growth-hackers/

“Defining A Growth Hacker: Building Growth into Your Team” at techcrunch.com/2012/10/21/defining-a-growthhacker-building-growthinto-your-team/

“How to Hire a Growth Hacker” at www.aginnt.com/post/64205739421/how-to-hire-agrowthhacker#.U2_ZiK1dXR1

“13 Critically Important Lessons from Over 50 Growth Hackers” at blog.kissmetrics.com/lessons-from-growth-hackers/

“What is a Growth Hacker? Does Your Startup Need a Growth Team?” at www.caneelian.com/2012/10/30/what-is-a-growth-hacker-does-yourstartup-need-a-growth-team/

 
Like all things online, these links can go away thanks to the changing nature of the web, but the links were all good at the time of this writing in mid-2014.
 
Growth Hacking Itself Will Evolve
 Growth hacking is itself an evolving and changing field. Even the definition of what it means to “grow” is changing in the face of the growing mobile revolution.
 Experts predict that by the end of 2014, there will be 90 million tablet computer users in the United States alone. Some of these people may lead their entire online lives without ever sitting down at a conventional desktop PC or opening a laptop. 
Knowing this, optimizing a user experience for the tablet generation will be much different than tailoring a site to meet the needs of a PC user. A good growth hacker doesn’t just stay on top of trends of this nature, but anticipates them and factors them into their ongoing strategy.
 That is both the daunting and exciting aspect of this new approach to marketing in the 21st century. It’s no longer a matter of thinking outside the box, but of redesigning the box, or even asking, “Why do we have a box in the first place?”
 
 
Afterword
 
While I was researching material for this book, I ran across a Slideshare presentation by Ryan Holiday entitled “19 Growth Hacker Quotes: Thoughts on the Future of Marketing” that seem to further support the notion I raised in the foreword that defining growth hacking is like nailing Jell-o to a tree.
Growth hackers have a common attitude, internal investigation process, and mentality unique among technologist and marketers. This mindset of data, creativity, and curiosity allows a growth hacker to accomplish the feat of grown a user base into the millions. — Andrew Chen, Entrepreneur and Technology Writer

A growth hacker works within the parameters of a scalable and repeatable method for growth, drive by product and inspired by data. A growth hacker lives at the intersection of data, product, and marketing.
— Aaron Ginn, Head of Grown, StumbleUpon

 
Growth hacking has a subtle message of “what have you done for me 
today?” You never stop as a growth hacker. Facebook still has a growth team and they have a billion users. - Blake Commagere, Founder of MediaSpike

“Growth hacking” is a recognition that when you focus on understanding your users and how they discover and adopt your products, you can build features that help you acquire and retain more users, rather than just spending marketing dollars. — Josh Elman, Partner at Greylock Partners

Growth hacking is the process and mindset of searching for k ways that your product to grow. It’s kind of like a mix between engineering and marketing. The key is to find untapped channels of customers that are motivated to use your product. — Dan Martell, Founder of Clarity

A growth hacker is someone who has thrown out the playbook of traditional marketing and replaced it with only what is testable, trackable, and scalable. Their tools are emails, pay-per-click ads, blogs, and platform APIs instead of commercials, publicity, and money.

 
Growth hacking tends to be more “experience” focused. This includes driving engagement and sharing within a product or spreading a product experience across networks. Effective growth hackers are relentless about running creative experiments and optimizing the components of the experiment until finding something that works. - Sean Ellis, CEO of Qualaroo

Perhaps my favorite however is by David Ogilvy, known as “the father of advertising.” It speaks to both the serious detail orientation of growth hacking and the relentless curiosity and urge to optimize that goes with it:
“I prefer the discipline of knowledge to the anarchy of ignorance. We pursue knowledge the way a pig pursues truffles.”
 
Growth hackers are all these things — and whatever else they need to be in the situation in which they find themselves. They are self-inventors in many ways, and re-inventors of most of the things with which they come into contact.
 That is, frankly, one of the most intriguing things about this way to market, the complete absence of “rules,” but an ever expanding playbook. If a growth hacker throws a Hail Mary pass, you can bet that he knows the prevailing wind speed, weight of the ball, and potential reach of the receiver in the end zone down to the millimeter.
 Now, if there’s two seconds left on the clock and he can get away with rigging the danged thing to hang up until that ball is caught and the ref’s arms are up in the air? He’ll do that, too.
 
