# 99designs
 
The online graphics design marketplace 99designs was founded in Melbourne, Australia in 2008 to create products via crowdsourcing. Designs are entered competitively for customer selection in a contest structure with the winner receiving cash payment. There is also an option to purchase templates and work with individual designers directly. Typical projects include logos, t-shirts, and websites.
 Traction for solid growth was actually built in to the concept from the beginning since it was a spinoff of SitePoint forums. Participating web designers on the forums occasionally competed informally in fictional logo contests. Ultimately someone asked for the real thing and the idea was born to spin off a company.
 99designs was profitable from year one because they began with proof of concept and then achieved fast internationalization by bootstrapping their existing U.S.-based traffic through the forums. The company opened in the United States in 2010 and secured $35 million in funding the following year. In 2012, after acquiring 12designer, 99designs entered the European market.
 The spinoff story is a good example of how growth hacking should follow inspiration and user demand. It would have been easy to blow off the request for a real-life logo contest as a flash in the pan, but the 99design organizers saw merit in the competition model.
 From the start, they understood the demands of market fit. This was behind their decision to keep their development team in Australia even when U.S. customers represented their largest market, and to remain localized to English-language jobs for the first three years.
 During that period, the company still worked with customers in 150 countries, but they were able to learn more about the markets they hoped to enter and to add to their existing pool of designers.
 When 99designs did enter the European market, they did so with the acquisition of an existing firm (12designer) that was already localized in five languages. At the time, 99designs was well capitalized and could afford to stretch their marketing budget.

By 2012, the site’s top designers were making upwards of $10,000 a month. In January 2012 alone, the entire 99design community earned a total $1.5 million. At that point, four years into its existence, the company paid out $28 million to its designers, who work on a commission model, earning anywhere from 30%-50% of the purchase price for their work.
 
 
 
 
